export const IS_AUTHENTICATED = 'IS_AUTHENTICATED';
export const LOGOUT = 'LOGOUT';
export const LOGINERROR = 'LOGINERROR';
export const AUTHSTART = 'AUTHSTART';

export const DRIVERINFO = 'DRIVERINFO';
export const DRIVERBALANCE = 'DRIVERBALANCE';

export const TRANSACTION = 'TRANSACTION';
export const TRANSACTIONERROR = 'TRANSACTIONERROR';

export const VEHICLEINFO = 'VEHICLEINFO';

export const DEACTIVATEDRIVER = 'DEACTIVATEDRIVER';


export const DRIVERRATINGS = 'DRIVERRATINGS';